### ISSUE TITLE
Listen error

### ISSUE THREAD

**Issue by yriveiro** [Kindari/SublimeXdebug#10]
Hi, 

I've got this error when I try to do a debug.

``` python
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./Xdebug.py", line 248, in thread_callback
  File "./Xdebug.py", line 119, in accept
AttributeError: 'NoneType' object has no attribute 'settimeout'
```

**Comment by miguelramos** [comment]
Same happens to me! One thing, how do your start the xdebug session? It goes to browser and just use XDEBUG_SESSION_START=test on url? And then sublime will capture this? Just tried but nothing happens and when clear happens the same as @yriveiro.

**Comment by yriveiro** [comment]
You replicate the same process that I.

It's a shame that this plugin doesn't work properly still.

**Comment by jotson** [comment]
Lots of changes in the latest version. Let us know if you are still having these issues. Also, look at the instructions in the new README to see how to automatically trigger your browser to start a debugging session.
