### ISSUE TITLE
SublimeXDebug Error on Mac

### ISSUE THREAD

**Issue by kenvunz** [Kindari/SublimeXdebug#23]
Got this error on when running SublimeXDebug on Mac Lion (10.7) and Sublime Text 2 (Build 2203)

Please take a look if you can

Cheers

``` python
Traceback (most recent call last):
  File "/Applications/Sublime Text 2.app/Contents/MacOS/sublime_plugin.py", line 356, in run_
    return self.run(edit, **args)
  File "./Xdebug.py", line 448, in run
  File "./Xdebug.py", line 467, in callback
AttributeError: 'NoneType' object has no attribute 'current'
```

**Comment by pdeszynski** [comment]
:+1: 
Every time when I'm using inside of a code `xdebug_break();` function, it stops and I'm getting this exception. Additionally xdebug just ignores breakpoints and moves forward if there's no `xdebug_break()` function.
