### ISSUE TITLE
Debug windows do not finish drawing

### ISSUE THREAD

**Issue by cpradio** [Kindari/SublimeXdebug#31]
I have python 2.6.6 and Sublime Text 2.0.1 Build 2217 on a Linux amd64 system.

The starting of debugging works fine, it launches chrome just fine, etc. But it won't finish drawing the debug windows so I can't tell it to continue playing when it gets to a breakpoint or see what the variables/output is.

I am at a lost on what to check next, any ideas?

**Comment by cpradio** [comment]
Here is what is in the console, if this helps anyone:

Traceback (most recent call last):
  File "./Xdebug.py", line 327, in gui_callback
  File "./Xdebug.py", line 97, in read
  File ".\xml\dom\minidom.py", line 1927, in parseString
  File ".\xml\dom\expatbuilder.py", line 32, in <module>
  File ".\xml\parsers\expat.py", line 4, in <module>
ImportError: No module named pyexpat

**Comment by cpradio** [comment]
Okay, so it seems it is due to the python2.6.zip that is packaged with sublime_text2.  I removed the zip file and created a symbolic link to /usr/lib/python2.6/ in the sublime_text2 lib folder and now it draws the xdebug windows just fine.
